name: Run CodeCov
on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt install python3-dev libssl-dev
        pip install uv
    - name: Install test dependencies
      run: |
        uv pip install -r test/requirements.txt
    - name: Install core repo
      run: |
        uv pip install -e .
    - name: Generate coverage report
      run: |
        uv run pytest --cov=ovos_gui --cov-report xml test/unittests
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/reports/
        fail_ci_if_error: true
        files: ./coverage.xml,!./cache
        flags: unittests
        name: codecov-umbrella
        verbose: true
