name: Run CodeCov
on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt install python3-dev libssl-dev
        python -m pip install build wheel
    - name: Install test dependencies
      run: |
          pip install -r test/requirements.txt
    - name: Install core repo
      run: |
        pip install -e .
    - name: Generate coverage report
      run: |
        pytest --cov=ovos_gui --cov-report xml test/unittests 
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/reports/
        fail_ci_if_error: true
        files: ./coverage.xml,!./cache
        flags: unittests
        name: codecov-umbrella
        verbose: true
