name: Ovoscope End-to-End Tests

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  ovoscope:
    uses: OpenVoiceOS/gh-automations/.github/workflows/ovoscope.yml@dev
    secrets: inherit
    with:
      runner: "ubuntu-latest"
      python_version: "3.11"
      install_extras: "test"
      test_path: "test/end2end/"
      bus_coverage: true
      bus_coverage_exclude: "^Thread-|^intents$|^skills$|^__core__$"
      pr_comment: true
